sonar.projectKey=my-angular-app
sonar.projectName=My Angular App
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/lcov/lcov.info
sonar.javascript.lcov.reportPaths=coverage/lcov/lcov.info